"""added ref to report

Revision ID: a0d99f8eaf63
Revises: 122110744562
Create Date: 2018-05-20 01:46:03.629198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d99f8eaf63'
down_revision = '122110744562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('reference_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report', 'reference_info_list', ['reference_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_column('report', 'reference_id')
    # ### end Alembic commands ###
