"""updated report table

Revision ID: b5b1c657c9ca
Revises: a0d99f8eaf63
Create Date: 2018-05-21 01:44:12.769252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b1c657c9ca'
down_revision = 'a0d99f8eaf63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report', sa.Column('status_details', sa.Text(), nullable=True))
    op.add_column('report', sa.Column('upload_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report', 'upload_date')
    op.drop_column('report', 'status_details')
    # ### end Alembic commands ###
