"""drop fuente column

Revision ID: c2a673754978
Revises: 00353cb9b31d
Create Date: 2018-05-13 15:40:59.216723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a673754978'
down_revision = '00353cb9b31d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_fuente_info', sa.Column('descripcion', sa.String(length=20), nullable=True))
    op.drop_column('catalogo_fuente_info', 'fuente_descripcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogo_fuente_info', sa.Column('fuente_descripcion', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('catalogo_fuente_info', 'descripcion')
    # ### end Alembic commands ###
